theme: minima
title: My Engineering Portfolio
author: Marko Sofroni
decription: Welcome to my personal portfolio! I am an engineering student at the University of Connecticut. This website showcases my background, education, projects, skills, and experiences as I continue to develop my knowledge and prepare for future career opportunities.
